name: Workflow dispatch

on:
  workflow_dispatch:

jobs:
  run:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: echo "Hello World"

    - name: Enviroment Variables
      env:
          CURRENT_DATE:'2024-10-25'
      run: echo '$CURRENT_DATE'
